### ISSUE TITLE
新增 老师 这一用户级别

### ISSUE THREAD

**Issue by tannineo** [acm309/PutongOJ#10]
原有用户级别为:
- 管理员
- 游客

需增加 老师:
- 可以建立group
- 修改group信息
- 处理group的加入申请
- 可以增加题目 并可以修改自己增加的题目
- 可以举办contest
- 针对任何实体的删除尽量不开放给老师 许多老师使用的时候出现过误删除

由于和其他功能的改进有重叠 也请查看其它issue

**Comment by lazzzis** [comment]
Closed, per https://github.com/acm309/PutongOJ-FE/commit/01783f4d16f8ae61672e7139a4607544c7e0a259
