### ISSUE TITLE
这个oj不支持spj吗

### ISSUE THREAD

**Issue by Zeng1998** [acm309/PutongOJ#36]
这个oj不支持spj吗

**Comment by lazzzis** [comment]
暂不支持

**Comment by Zeng1998** [comment]
> 暂不支持

我看后台judger是有spj选项的，请问是出于什么原因没加上呢？

**Comment by lazzzis** [comment]
judger 是 fork https://github.com/KIDx/Judger 的，并不是我们自己开发的。选择这个 judger 是因为感觉比较容易上手。

没有加上仅仅是因为 1. 开始时并没有这需求 2. 当时并不了解 spj

**Comment by Zeng1998** [comment]
> judger 是 fork https://github.com/KIDx/Judger 的，并不是我们自己开发的。选择这个 judger 是因为感觉比较容易上手。
> 
> 没有加上仅仅是因为 1. 开始时并没有这需求 2. 当时并不了解 spj

好的谢谢，了解了，我还以为是有什么坑
